version: '3.8'

volumes:
  postgres_data:
  staticfiles:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
  web:
    image: johnydubov/api_yamdb:latest
    restart: always
    volumes:
      - staticfiles:/code/static
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.6
    restart: always
    volumes:
      - staticfiles:/static
      - ./nginx/host.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - web
